name: ViShopPlugin
version: '2.1'
api-version: 1.13
main: pl.vishop.plugin.bukkit.BukkitViShopPlugin
description: "Wykonuj zamówienia ze swojego sklepu ViShop"
website: https://vishop.pl/
author: "VIshop-plugin Contributors"
